### ISSUE TITLE
Something wrong with HotSpot

### ISSUE THREAD

**Issue by wyclike** [IFTE-EDA/Corblivar#2]
What a great work! We want to follow your work,but we meet some trouble:
Perform HotSpot run ...
/home/wyc/HotSpot/hotspot -c hotspot_heatsink.config -f n300_HotSpot_Si_active_1.flp -p n300_HotSpot.ptrace -grid_steady_file n300_HotSpot.steady.grid -steady_file n300_HotSpot.steady -detailed_3D on -grid_layer_file n300_HotSpot.lcf > n300_HotSpot.txt
error: error opening file n300_HotSpot_Si_active_1.flp

real    0m0.006s
user    0m0.005s
sys     0m0.015s
ls: cannot access '*.gp': No such file or directory

I believe I have successfully configured and compiled according to the readme document, but when I run `bash run8.sh`, an error occurs.

**Comment by wyclike** [comment]
I have no idea about the "n200_HotSpot_Si_active_1.flp", is it created by HotSpot? Or is it provided by the benchmark and feed it to the HotSpot as one of the input files?(But i coulnd find this file)

**Comment by jknechtel** [comment]
Which steps exactly did you take to get this error?

**Comment by jknechtel** [comment]
But in general, these flp files are generated by Corblivar. Only then you can run HotSpot. Please follow the order of steps as outlined in the documentation. Thanks!
