### ISSUE TITLE
I met trouble after run bash gp.sh

### ISSUE THREAD

**Issue by wyclike** [IFTE-EDA/Corblivar#4]
Firsrtly,I have successfully run the command:../Corblivar n100  /home/wyc/Corblivar/exp/configs/3dies/regular/n100_soft.conf  benches/
and it generated some file ,including:*.data,*.gp,*.flp,*.ptrace and so on.

Secondly,I run the gp.sh，and it generate some .pdf like :n100_1_thermal.gp.pdf.

But, i found that all xxx_1_HotSpot.gp.pdf couldn't be open because the wrong that ""n100_3_HotSpot.gp" line 54: warning: Cannot find or open file "n100_HotSpot.steady.grid.gp_data.layer_9", i interface that is the hotSpot could run in right way.

Do u have any idea?

**Comment by jknechtel** [comment]
I'm afraid the last part of your problem description is not very clear. But I think you're trying to view the thermal map obtained from HotSpot? For that, you'd have to run HotSpot first of course. Please see again the comments I have provided recently for https://github.com/DfX-NYUAD/Corblivar/issues/2 as well as https://github.com/DfX-NYUAD/Corblivar/issues/3

Best, Johann

**Comment by wyclike** [comment]
Thanks，but i still can't generate the right “n100_1_HotSpot.gp.pdf”.
After run HosSpot first，i generate ：①n100_HotSpot.lcf；②n100_HotSpot.ptrace; ③n100_HotSpot.steady;④n100_HotSpot.steady.grid;⑤:n100_HotSpot.txt;
Then ,i run gnuplot n100_1_HotSpot.gp but still failed for :"n100_3_HotSpot.gp" line 55: warning: Cannot find or open file "n100_HotSpot.steady.grid.gp_data.layer_9"

Actually,i found another question is that in the n100_HotSpot.txt,it include some wrong information like:layer_13_Si_passive_3_27:50	295.42 ,and i have only 3 layer ,what is the 13 layer in it?

**Comment by wyclike** [comment]
i mean that although i have run the HotSpot.sh, but i still haven't the file ""n100_HotSpot.steady.grid.gp_data.layer_{number}".I have only the file like "n100_HotSpot.steady.grid" or  "n100_HotSpot.steady"

**Comment by jknechtel** [comment]
Few thoughts here. Are you sure that HotSpot.sh did run correctly? Did you map the HS variable to your local installation of HotSpot? Did you use the tailored HotSpot version from https://github.com/jknechtel/HotSpot ?

As for the layer information in the txt file, these are material layers, not 3D layers, so that number is expected to be larger there.

**Comment by wyclike** [comment]
Thank a lot！After i change the version of hotspot to the link you provided,it work! cool~ What a solid work you did~

**Comment by wyclike** [comment]
Hi,i have do something work with this solid work.And i have used some technology to optimize the thermal analysis process,meaning that compared to the power-thurring method, I now have a faster and more accurate technology that can obtain thermal data for each layer. And i want to do it deeper ,such as  i want to use the precise thermal data to guide the simulated annealing process  to obtain better solutions.  Therefore, I would like to take the liberty of consulting your perspective and insights through this channel, and to gain some inspiration from them.  Thank you!

**Comment by jknechtel** [comment]
Great to hear that, and sure, let's do that. Let me know if you have specific questions. Instead of going through this channel of issues, tough, maybe let's use the Wiki function. Or, you could directly implement your changes into a fork and then create some pull request.
